# Generated by ChatGPT on 2024-06-01
# Converts existing annotation format for Mapillary Traffic Sign Dataset to YOLO format, with configurable filtering and splitting.

from pathlib import Path
import json
import random
import os
import shutil
from collections import Counter
from typing import Optional

# ============================================================
# Configuration
# ============================================================

# Input folders
IMAGE_DIR = Path("D:/raw_images/images")
ANNOTATION_DIR = Path("dataset/mtsd_v2_fully_annotated/annotations")

# Output folder
OUTPUT_DIR = Path("D:/yolo_dataset")

# Image extensions to consider
IMAGE_SUFFIXES = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

# Random seed for reproducibility
RANDOM_SEED = 42

# Split ratios for POSITIVE images only
TRAIN_RATIO = 0.70
VAL_RATIO = 0.15
TEST_RATIO = 0.15

# Empty-image ratios relative to positive counts in each split
# Example: train positives * 0.55 -> number of empty train images
TRAIN_EMPTY_RATIO = 0.55
VAL_EMPTY_RATIO = 0.50
TEST_EMPTY_RATIO = 0.50

# Whether to skip annotations where properties["included"] == False
SKIP_NOT_INCLUDED = True

# Restrict to sign-like labels only
USE_LABEL_FILTER = True
ALLOWED_PREFIXES = (
    "regulatory--",
    "warning--",
    "information--",
    "complementary--",
)
ALLOWED_EXACT = {
    "other-sign",
}

# Single-class YOLO mapping
CLASS_NAMES = {
    0: "traffic_sign"
}

# Whether to keep images with no usable boxes in the final dataset
INCLUDE_EMPTY_IMAGES = True

# If True, delete OUTPUT_DIR first
CLEAR_OUTPUT_DIR = True


# ============================================================
# Helpers
# ============================================================

def is_allowed_label(label: str) -> bool:
    if label in ALLOWED_EXACT:
        return True
    return label.startswith(ALLOWED_PREFIXES)


def map_label_to_class(label: str) -> Optional[int]:
    """
    Map all allowed labels to one class: traffic_sign.
    Return None for labels that should be skipped.
    """
    if USE_LABEL_FILTER and not is_allowed_label(label):
        return None
    return 0


def clamp(value: float, low: float = 0.0, high: float = 1.0) -> float:
    return max(low, min(high, value))


def convert_bbox_to_yolo(
    xmin: float,
    ymin: float,
    xmax: float,
    ymax: float,
    img_w: float,
    img_h: float
) -> tuple[float, float, float, float]:
    box_w = xmax - xmin
    box_h = ymax - ymin
    x_center = xmin + box_w / 2.0
    y_center = ymin + box_h / 2.0

    x_center /= img_w
    y_center /= img_h
    box_w /= img_w
    box_h /= img_h

    return (
        clamp(x_center),
        clamp(y_center),
        clamp(box_w),
        clamp(box_h),
    )


def ensure_output_dirs(base_dir: Path) -> None:
    for split in ("train", "val", "test"):
        (base_dir / "images" / split).mkdir(parents=True, exist_ok=True)
        (base_dir / "labels" / split).mkdir(parents=True, exist_ok=True)


def clear_output_dir(base_dir: Path) -> None:
    if base_dir.exists():
        shutil.rmtree(base_dir)


def find_matching_json(image_path: Path) -> Optional[Path]:
    candidate = ANNOTATION_DIR / f"{image_path.stem}.json"
    if candidate.exists():
        return candidate
    return None


def load_json(json_path: Path) -> dict:
    with open(json_path, "r", encoding="utf-8") as f:
        return json.load(f)


def extract_yolo_lines(data: dict) -> list[str]:
    """
    Convert valid JSON annotations to YOLO-format lines.
    """
    img_w = data.get("width")
    img_h = data.get("height")

    if not img_w or not img_h:
        return []

    yolo_lines: list[str] = []

    for obj in data.get("objects", []):
        label = obj.get("label")
        if not label:
            continue

        class_id = map_label_to_class(label)
        if class_id is None:
            continue

        props = obj.get("properties", {}) or {}
        if SKIP_NOT_INCLUDED and props.get("included") is False:
            continue

        bbox = obj.get("bbox", {}) or {}
        xmin = bbox.get("xmin")
        ymin = bbox.get("ymin")
        xmax = bbox.get("xmax")
        ymax = bbox.get("ymax")

        if None in (xmin, ymin, xmax, ymax):
            continue

        if xmax <= xmin or ymax <= ymin:
            continue

        x_center, y_center, box_w, box_h = convert_bbox_to_yolo(
            xmin, ymin, xmax, ymax, img_w, img_h
        )

        if box_w <= 0 or box_h <= 0:
            continue

        yolo_lines.append(
            f"{class_id} {x_center:.6f} {y_center:.6f} {box_w:.6f} {box_h:.6f}"
        )

    return yolo_lines


def split_list(items: list, train_ratio: float, val_ratio: float, test_ratio: float) -> tuple[list, list, list]:
    if not abs((train_ratio + val_ratio + test_ratio) - 1.0) < 1e-9:
        raise ValueError("Split ratios must sum to 1.0")

    n = len(items)
    n_train = int(n * train_ratio)
    n_val = int(n * val_ratio)
    n_test = n - n_train - n_val

    train_items = items[:n_train]
    val_items = items[n_train:n_train + n_val]
    test_items = items[n_train + n_val:]

    assert len(train_items) + len(val_items) + len(test_items) == n
    assert len(test_items) == n_test

    return train_items, val_items, test_items


def write_yaml(output_dir: Path) -> None:
    yaml_path = output_dir / "dataset.yaml"
    with open(yaml_path, "w", encoding="utf-8") as f:
        f.write(f"path: {output_dir.resolve().as_posix()}\n")
        f.write("train: images/train\n")
        f.write("val: images/val\n")
        f.write("test: images/test\n")
        f.write("\n")
        f.write("names:\n")
        for class_id in sorted(CLASS_NAMES):
            f.write(f"  {class_id}: {CLASS_NAMES[class_id]}\n")


def copy_image_and_write_label(
    image_path: Path,
    yolo_lines: list[str],
    split_name: str,
    output_dir: Path
) -> None:
    out_img = output_dir / "images" / split_name / image_path.name
    out_lbl = output_dir / "labels" / split_name / f"{image_path.stem}.txt"

    shutil.copy2(image_path, out_img)

    with open(out_lbl, "w", encoding="utf-8") as f:
        for line in yolo_lines:
            f.write(line + "\n")


# ============================================================
# Main
# ============================================================

def main() -> None:
    random.seed(RANDOM_SEED)

    if CLEAR_OUTPUT_DIR:
        clear_output_dir(OUTPUT_DIR)
    ensure_output_dirs(OUTPUT_DIR)

    image_paths = sorted(
        [p for p in IMAGE_DIR.iterdir() if p.suffix.lower() in IMAGE_SUFFIXES]
    )

    total_images = len(image_paths)
    matched_pairs: list[tuple[Path, Path, list[str]]] = []
    missing_json_images: list[str] = []
    unreadable_jsons: list[tuple[str, str]] = []

    positive_items: list[tuple[Path, Path, list[str]]] = []
    empty_items: list[tuple[Path, Path, list[str]]] = []

    label_counter = Counter()
    total_boxes = 0

    print("Scanning images and annotations...")

    for image_path in image_paths:
        json_path = find_matching_json(image_path)
        if json_path is None:
            missing_json_images.append(image_path.name)
            continue

        try:
            data = load_json(json_path)
        except Exception as e:
            unreadable_jsons.append((json_path.name, str(e)))
            continue

        yolo_lines = extract_yolo_lines(data)
        matched_pairs.append((image_path, json_path, yolo_lines))

        if yolo_lines:
            positive_items.append((image_path, json_path, yolo_lines))
            total_boxes += len(yolo_lines)

            for line in yolo_lines:
                class_id = int(line.split()[0])
                label_counter[class_id] += 1
        else:
            empty_items.append((image_path, json_path, yolo_lines))

    print(f"Total images found: {total_images}")
    print(f"Matched image/JSON pairs: {len(matched_pairs)}")
    print(f"Missing JSON images: {len(missing_json_images)}")
    print(f"Unreadable JSON files: {len(unreadable_jsons)}")
    print(f"Positive images: {len(positive_items)}")
    print(f"Empty images after filtering: {len(empty_items)}")

    if not positive_items:
        raise RuntimeError("No positive images found after filtering. Nothing to train on.")

    # Shuffle positive and empty lists independently
    random.shuffle(positive_items)
    random.shuffle(empty_items)

    # Split positive images first
    train_pos, val_pos, test_pos = split_list(
        positive_items,
        TRAIN_RATIO,
        VAL_RATIO,
        TEST_RATIO
    )

    # Sample empty images for each split
    if INCLUDE_EMPTY_IMAGES:
        train_empty_target = min(len(empty_items), int(len(train_pos) * TRAIN_EMPTY_RATIO))
        remaining_after_train = len(empty_items) - train_empty_target

        val_empty_target = min(remaining_after_train, int(len(val_pos) * VAL_EMPTY_RATIO))
        remaining_after_val = remaining_after_train - val_empty_target

        test_empty_target = min(remaining_after_val, int(len(test_pos) * TEST_EMPTY_RATIO))

        train_empty = empty_items[:train_empty_target]
        val_empty = empty_items[train_empty_target:train_empty_target + val_empty_target]
        test_empty = empty_items[
            train_empty_target + val_empty_target:
            train_empty_target + val_empty_target + test_empty_target
        ]
    else:
        train_empty = []
        val_empty = []
        test_empty = []

    train_items = train_pos + train_empty
    val_items = val_pos + val_empty
    test_items = test_pos + test_empty

    # Shuffle each split again so positives/empties are mixed
    random.shuffle(train_items)
    random.shuffle(val_items)
    random.shuffle(test_items)

    # Write files
    print("\nWriting YOLO dataset...")
    split_box_counts = {"train": 0, "val": 0, "test": 0}
    split_positive_counts = {"train": 0, "val": 0, "test": 0}
    split_empty_counts = {"train": 0, "val": 0, "test": 0}

    for split_name, items in (
        ("train", train_items),
        ("val", val_items),
        ("test", test_items),
    ):
        for image_path, _json_path, yolo_lines in items:
            copy_image_and_write_label(image_path, yolo_lines, split_name, OUTPUT_DIR)

            if yolo_lines:
                split_positive_counts[split_name] += 1
                split_box_counts[split_name] += len(yolo_lines)
            else:
                split_empty_counts[split_name] += 1

    write_yaml(OUTPUT_DIR)

    # Final report
    print("\n=== Final Dataset Summary ===")
    print(f"Output directory: {OUTPUT_DIR.resolve()}")
    print()

    for split_name in ("train", "val", "test"):
        total_split = split_positive_counts[split_name] + split_empty_counts[split_name]
        print(f"{split_name.upper()}:")
        print(f"  total images:    {total_split}")
        print(f"  positive images: {split_positive_counts[split_name]}")
        print(f"  empty images:    {split_empty_counts[split_name]}")
        print(f"  total boxes:     {split_box_counts[split_name]}")
        print()

    print("Class names:")
    for class_id, name in CLASS_NAMES.items():
        print(f"  {class_id}: {name}")

    print("\nDone.")

    if missing_json_images:
        print("\nSample missing JSON image files:")
        for name in missing_json_images[:20]:
            print(f"  - {name}")

    if unreadable_jsons:
        print("\nSample unreadable JSON files:")
        for name, err in unreadable_jsons[:10]:
            print(f"  - {name}: {err}")


if __name__ == "__main__":
    main()