#!/usr/bin/env python3
"""
Lazy data loading utilities for CTU-13 PyTorch Geometric `.pt` graph files.

This module is designed to work with manifests generated by:
- ctu13_pt_handoff_prep.py

It supports:
- fixed train/val/test split CSVs
- grouped-CV fold CSVs
- absolute or relative graph paths
- lazy loading (graphs are loaded on demand, not all into RAM at once)

Dependencies:
- torch
- torch-geometric

It does NOT require:
- pandas
- numpy

Example:
    from ctu13_pyg_loader import build_fixed_split_loaders

    train_loader, val_loader, test_loader = build_fixed_split_loaders(
        metadata_dir="./ctu13_handoff/metadata",
        graph_root="./ctu13_pyg",     # required if manifest uses relative graph paths
        batch_size=8,
        num_workers=0,
    )
"""

from __future__ import annotations

import argparse
import csv
import json
from collections import Counter
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Sequence, Tuple

import torch
from torch.utils.data import Dataset
from torch_geometric.loader import DataLoader
from torch_geometric.data import Data  # noqa: F401  # for torch.load deserialization


@dataclass
class GraphRecord:
    scenario_name: str
    family: str
    graph_path: str
    graph_relpath: str
    source_file: str
    window_start: str
    window_end: str
    num_nodes: int
    num_edges: int
    num_node_features: int
    num_edge_features: int
    num_labeled_nodes: int
    num_positive_nodes: int
    num_negative_nodes: int
    num_unknown_nodes: int
    split: str = ""

    @classmethod
    def from_row(cls, row: Dict[str, str]) -> "GraphRecord":
        def _to_int(key: str) -> int:
            value = row.get(key, "")
            return int(value) if str(value).strip() else 0

        return cls(
            scenario_name=row.get("scenario_name", ""),
            family=row.get("family", ""),
            graph_path=row.get("graph_path", ""),
            graph_relpath=row.get("graph_relpath", ""),
            source_file=row.get("source_file", ""),
            window_start=row.get("window_start", ""),
            window_end=row.get("window_end", ""),
            num_nodes=_to_int("num_nodes"),
            num_edges=_to_int("num_edges"),
            num_node_features=_to_int("num_node_features"),
            num_edge_features=_to_int("num_edge_features"),
            num_labeled_nodes=_to_int("num_labeled_nodes"),
            num_positive_nodes=_to_int("num_positive_nodes"),
            num_negative_nodes=_to_int("num_negative_nodes"),
            num_unknown_nodes=_to_int("num_unknown_nodes"),
            split=row.get("split", ""),
        )


def safe_torch_load(path: Path, map_location: str = "cpu") -> Any:
    """
    Load an object with compatibility across Torch versions.

    Torch 2.6 changed the default behavior of torch.load toward weights-only.
    PyG Data objects require weights_only=False.
    """
    try:
        return torch.load(path, map_location=map_location, weights_only=False)
    except TypeError:
        return torch.load(path, map_location=map_location)



def read_manifest(csv_path: str | Path) -> List[GraphRecord]:
    csv_path = Path(csv_path)
    with csv_path.open("r", newline="", encoding="utf-8") as fh:
        rows = list(csv.DictReader(fh))
    return [GraphRecord.from_row(row) for row in rows]



def resolve_graph_path(record: GraphRecord, graph_root: Optional[str | Path] = None) -> Path:
    graph_path = Path(record.graph_path)
    if graph_path.is_absolute():
        return graph_path

    if graph_root is None:
        raise ValueError(
            "Manifest uses relative graph paths. Provide graph_root or generate the manifest with --path-mode absolute."
        )
    return Path(graph_root).resolve() / graph_path


class PTGraphDataset(Dataset):
    """Lazy-loading dataset for PyG graph `.pt` files referenced by a CSV manifest."""

    def __init__(self, records: Sequence[GraphRecord], graph_root: Optional[str | Path] = None):
        self.records = list(records)
        self.graph_root = Path(graph_root).resolve() if graph_root is not None else None

    def __len__(self) -> int:
        return len(self.records)

    def __getitem__(self, idx: int) -> Any:
        record = self.records[idx]
        path = resolve_graph_path(record, self.graph_root)
        graph = safe_torch_load(path, map_location="cpu")
        return graph



def build_loader(
    records: Sequence[GraphRecord],
    graph_root: Optional[str | Path] = None,
    batch_size: int = 8,
    shuffle: bool = False,
    num_workers: int = 0,
    pin_memory: bool = False,
    persistent_workers: bool = False,
) -> DataLoader:
    dataset = PTGraphDataset(records=records, graph_root=graph_root)
    return DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=(persistent_workers and num_workers > 0),
    )



def build_fixed_split_loaders(
    metadata_dir: str | Path,
    graph_root: Optional[str | Path] = None,
    batch_size: int = 8,
    num_workers: int = 0,
    pin_memory: bool = False,
    persistent_workers: bool = False,
) -> Tuple[DataLoader, DataLoader, DataLoader]:
    metadata_dir = Path(metadata_dir)
    train_records = read_manifest(metadata_dir / "split_train.csv")
    val_records = read_manifest(metadata_dir / "split_val.csv")
    test_records = read_manifest(metadata_dir / "split_test.csv")

    train_loader = build_loader(
        train_records,
        graph_root=graph_root,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=persistent_workers,
    )
    val_loader = build_loader(
        val_records,
        graph_root=graph_root,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=persistent_workers,
    )
    test_loader = build_loader(
        test_records,
        graph_root=graph_root,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=persistent_workers,
    )
    return train_loader, val_loader, test_loader



def build_fold_loaders(
    fold_dir: str | Path,
    graph_root: Optional[str | Path] = None,
    batch_size: int = 8,
    num_workers: int = 0,
    pin_memory: bool = False,
    persistent_workers: bool = False,
) -> Tuple[DataLoader, DataLoader, DataLoader]:
    fold_dir = Path(fold_dir)
    train_records = read_manifest(fold_dir / "train.csv")
    val_records = read_manifest(fold_dir / "val.csv")
    test_records = read_manifest(fold_dir / "test.csv")

    train_loader = build_loader(
        train_records,
        graph_root=graph_root,
        batch_size=batch_size,
        shuffle=True,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=persistent_workers,
    )
    val_loader = build_loader(
        val_records,
        graph_root=graph_root,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=persistent_workers,
    )
    test_loader = build_loader(
        test_records,
        graph_root=graph_root,
        batch_size=batch_size,
        shuffle=False,
        num_workers=num_workers,
        pin_memory=pin_memory,
        persistent_workers=persistent_workers,
    )
    return train_loader, val_loader, test_loader



def summarize_records(records: Sequence[GraphRecord]) -> Dict[str, Any]:
    scenario_counts = Counter(r.scenario_name for r in records)
    family_counts = Counter(r.family for r in records)
    return {
        "num_graphs": len(records),
        "num_scenarios": len(scenario_counts),
        "num_families": len(family_counts),
        "graphs_per_scenario": dict(sorted(scenario_counts.items())),
        "graphs_per_family": dict(sorted(family_counts.items())),
        "total_labeled_nodes": sum(r.num_labeled_nodes for r in records),
        "total_positive_nodes": sum(r.num_positive_nodes for r in records),
        "total_negative_nodes": sum(r.num_negative_nodes for r in records),
        "total_unknown_nodes": sum(r.num_unknown_nodes for r in records),
    }



def summarize_fixed_split(metadata_dir: str | Path) -> Dict[str, Any]:
    metadata_dir = Path(metadata_dir)
    train_records = read_manifest(metadata_dir / "split_train.csv")
    val_records = read_manifest(metadata_dir / "split_val.csv")
    test_records = read_manifest(metadata_dir / "split_test.csv")
    return {
        "train": summarize_records(train_records),
        "val": summarize_records(val_records),
        "test": summarize_records(test_records),
    }



def summarize_fold(fold_dir: str | Path) -> Dict[str, Any]:
    fold_dir = Path(fold_dir)
    train_records = read_manifest(fold_dir / "train.csv")
    val_records = read_manifest(fold_dir / "val.csv")
    test_records = read_manifest(fold_dir / "test.csv")
    return {
        "train": summarize_records(train_records),
        "val": summarize_records(val_records),
        "test": summarize_records(test_records),
    }



def peek_first_batch(loader: DataLoader) -> Dict[str, Any]:
    batch = next(iter(loader))
    summary = {
        "x_shape": tuple(batch.x.shape) if getattr(batch, "x", None) is not None else None,
        "edge_index_shape": tuple(batch.edge_index.shape) if getattr(batch, "edge_index", None) is not None else None,
        "edge_attr_shape": tuple(batch.edge_attr.shape) if getattr(batch, "edge_attr", None) is not None else None,
        "y_shape": tuple(batch.y.shape) if getattr(batch, "y", None) is not None else None,
        "labeled_nodes_in_batch": int(batch.labeled_mask.sum().item()) if getattr(batch, "labeled_mask", None) is not None else None,
        "num_graphs_in_batch": int(batch.num_graphs) if hasattr(batch, "num_graphs") else None,
    }
    return summary



def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Build and inspect PyG loaders from CTU-13 split manifests.")
    parser.add_argument("--metadata-dir", default=None, help="Directory containing split_train.csv / split_val.csv / split_test.csv")
    parser.add_argument("--fold-dir", default=None, help="Directory containing one fold's train.csv / val.csv / test.csv")
    parser.add_argument("--graph-root", default=None, help="Required if graph paths in the CSV are relative")
    parser.add_argument("--batch-size", type=int, default=8, help="Batch size for the demo loader build")
    parser.add_argument("--num-workers", type=int, default=0, help="DataLoader workers")
    parser.add_argument("--pin-memory", action="store_true", help="Enable pin_memory on loaders")
    parser.add_argument("--persistent-workers", action="store_true", help="Enable persistent_workers when num_workers > 0")
    parser.add_argument("--print-summary", action="store_true", help="Print split summary JSON")
    parser.add_argument("--peek-batch", action="store_true", help="Load one train batch and print its shapes")
    return parser.parse_args()



def main() -> None:
    args = parse_args()
    if bool(args.metadata_dir) == bool(args.fold_dir):
        raise ValueError("Provide exactly one of --metadata-dir or --fold-dir")

    if args.metadata_dir:
        summary = summarize_fixed_split(args.metadata_dir)
        if args.print_summary:
            print(json.dumps(summary, indent=2))
        if args.peek_batch:
            train_loader, _, _ = build_fixed_split_loaders(
                metadata_dir=args.metadata_dir,
                graph_root=args.graph_root,
                batch_size=args.batch_size,
                num_workers=args.num_workers,
                pin_memory=args.pin_memory,
                persistent_workers=args.persistent_workers,
            )
            print(json.dumps(peek_first_batch(train_loader), indent=2))
    else:
        summary = summarize_fold(args.fold_dir)
        if args.print_summary:
            print(json.dumps(summary, indent=2))
        if args.peek_batch:
            train_loader, _, _ = build_fold_loaders(
                fold_dir=args.fold_dir,
                graph_root=args.graph_root,
                batch_size=args.batch_size,
                num_workers=args.num_workers,
                pin_memory=args.pin_memory,
                persistent_workers=args.persistent_workers,
            )
            print(json.dumps(peek_first_batch(train_loader), indent=2))


if __name__ == "__main__":
    main()
